name: 🐛 Bug Fix
description: 버그 수정
title: "[FIX] "
labels: ["bug"]

body:
  - type: textarea
    attributes:
      label: 버그 설명
      placeholder: 어떤 문제가 발생했는지 작성
    validations:
      required: true

  - type: textarea
    attributes:
      label: 재현 방법
      placeholder: 어떻게 하면 발생하는지 단계별 설명

  - type: textarea
    attributes:
      label: 기대 동작
      placeholder: 정상적으로 어떻게 동작해야 하는지

  - type: dropdown
    attributes:
      label: 대상 브랜치
      options:
        - develop

  - type: textarea
    attributes:
      label: 추가 정보
      placeholder: 로그, 스크린샷 등
