# 1. 빌드 단계
FROM gradle:8.14-jdk17 AS builder

WORKDIR /build

COPY . .

RUN gradle clean build -x test --no-daemon


# 2. 실행 단계
FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY --from=builder /build/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
